apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx-hello
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
  - host: hello.env.companydomain.com.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-nginx-hello
            port:
              number: 80
  tls:
  - hosts:
    - hello.env.companydomain.com.br
    secretName: hello-env-k8s-tls
